create table course (credits smallint not null, id varchar(255) not null, name varchar(255), primary key (id));
create table courses_faculties (course_id varchar(255) not null, faculty_id varchar(255) not null);
create table faculty (id varchar(255) not null, institute_id varchar(255), name varchar(255), primary key (id));
create table groups (id varchar(255) not null, name varchar(255), primary key (id));
create table groups_courses (course_id varchar(255) not null, group_id varchar(255) not null);
create table institute (id varchar(255) not null, name varchar(255), primary key (id));
create table lesson (group_id varchar(255), id varchar(255) not null, location varchar(255), name varchar(255), teacher_id varchar(255), primary key (id));
create table mark (mark_value smallint not null, feedback varchar(255), id varchar(255) not null, student_id varchar(255), primary key (id));
create table student (first_name varchar(255), group_id varchar(255), id varchar(255) not null, last_name varchar(255), login varchar(255), password varchar(255), primary key (id));
create table task (is_compulsory boolean not null, deadline timestamp(6), course_id varchar(255), description varchar(255), id varchar(255) not null, mark_id varchar(255) unique, status varchar(255) check (status in ('NOT_COMPLETED','UNDER_REVIEW','REVIEWED')), student_id varchar(255), title varchar(255), user_answer varchar(255), primary key (id));
create table teacher (first_name varchar(255), id varchar(255) not null, last_name varchar(255), login varchar(255), password varchar(255), primary key (id));
create table teachers_courses (course_id varchar(255) not null, teacher_id varchar(255) not null);
create table timeslot (local_date date, end_time timestamp(6), start_time timestamp(6), id varchar(255) not null, primary key (id));
create table timetable (group_id varchar(255) unique, id varchar(255) not null, primary key (id));
create table timetable_entry (id varchar(255) not null, lesson_id varchar(255), timeslot_id varchar(255) unique, timetable_id varchar(255), primary key (id));
alter table if exists courses_faculties add constraint FK6d1k7su5lauk144hdnf8m36f7 foreign key (faculty_id) references course;
alter table if exists courses_faculties add constraint FKd14cb2f7on6cus7slqrdll782 foreign key (course_id) references faculty;
alter table if exists faculty add constraint FKler2fm94weubb9p9t9g8j688t foreign key (institute_id) references institute;
alter table if exists groups_courses add constraint FK4dtqgjnc4g2xj9a5enrwg5qo5 foreign key (course_id) references groups;
alter table if exists groups_courses add constraint FK765hdk2erju5p8kji9tv076qp foreign key (group_id) references course;
alter table if exists lesson add constraint FKbv4ah6ibkgynpwx3ycarrwgj foreign key (group_id) references groups;
alter table if exists lesson add constraint FK9yhaoqrjxt5gwmn6icp1lf35n foreign key (teacher_id) references teacher;
alter table if exists mark add constraint FKcwocngy0rfmqdhqwm3qlrfamx foreign key (student_id) references student;
alter table if exists student add constraint FKsflcrdigyrhbqi27vvioiw53q foreign key (group_id) references groups;
alter table if exists task add constraint FKc06t5km0dmc9hktw7n3p6xd52 foreign key (course_id) references course;
alter table if exists task add constraint FKkk28ko2mvxht8uy4ayhhltvbh foreign key (mark_id) references mark;
alter table if exists task add constraint FK3r5969r125bafo5ow7i6dwncy foreign key (student_id) references student;
alter table if exists teachers_courses add constraint FKeu9fcg3kmrschds3fe4ps21xy foreign key (course_id) references teacher;
alter table if exists teachers_courses add constraint FKaspju64aodh18je2qxjxe5g3c foreign key (teacher_id) references course;
alter table if exists timetable add constraint FKexq74jm7or3issb9iey2m340t foreign key (group_id) references groups;
alter table if exists timetable_entry add constraint FK9yuyvfh09m6wf2hcxvvbye926 foreign key (lesson_id) references lesson;
alter table if exists timetable_entry add constraint FK9h0c1ia3b6g6p1mbwm1vw23fh foreign key (timeslot_id) references timeslot;
alter table if exists timetable_entry add constraint FKhl8jrtlfksu2veh0rvb5etlym foreign key (timetable_id) references timetable;
